version: '3.3'
services:
  kaldi:
    image: "akeartit/official-kaldi-model"
  web:
    image: "danijel3/kaldi-webrtc"
    volumes:
      - ./servers.json:/server/servers.json
    ports:
      - "8080:8080"